# Generated by Django 2.0.1 on 2018-01-26 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(help_text='The instrument manufacturer', max_length=50)),
                ('model', models.CharField(help_text='The instrument model', max_length=50)),
                ('instrument_name', models.CharField(help_text='The name that will be displayed to users', max_length=50)),
                ('year', models.DateField(help_text='The year the instrument was obtained. Format: YYYY-MM-DD')),
                ('location', models.CharField(help_text='Where the instrument can be found', max_length=50)),
                ('image', models.ImageField(default='C:\\Users\\gavin\\django\\booking\\booking_system\\static\\img\\10546i3DAC5A5993C8BC8C.jpg', upload_to='C:\\Users\\gavin\\django\\booking\\booking_system\\static\\img')),
                ('under_maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Type of instrument', max_length=20)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_manager.InstrumentCategory'),
        ),
    ]
