# Generated by Django 2.0.1 on 2018-01-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='C:\\Users\\gavin\\django\\booking\\booking_system\\static\\img\\10546i3DAC5A5993C8BC8C.jpg', upload_to='img/'),
        ),
    ]
