# Generated by Django 2.0.1 on 2018-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0002_auto_20180201_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='C:\\Users\\gavin\\django\\booking\\booking_system\\static\\img\\10546i3DAC5A5993C8BC8C.jpg', upload_to=''),
        ),
    ]
