# Generated by Django 2.0.1 on 2018-01-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0004_auto_20180201_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img'),
        ),
    ]
