# Generated by Django 2.0.1 on 2018-02-01 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_manager.Instrument'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
