# Generated by Django 2.0.2 on 2018-02-11 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0020_auto_20180210_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Calender_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(help_text='Name of settings group', max_length=50)),
                ('number_of_days', models.IntegerField(default=7, help_text='Number of days to be displayed in view')),
                ('first_session_time', models.TimeField(default='00:00:00', help_text='Time of first session')),
                ('last_session_time', models.TimeField(default='23:00:00', help_text='Time of last session')),
                ('time_interval', models.IntegerField(default=60, help_text='Number of minutes per session')),
                ('number_of_sessions', models.IntegerField(default=24, help_text='Number of sessions per day')),
                ('active', models.BooleanField(default=False, help_text='Set active to use this settings group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 35, 42, 736598)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 35, 42, 736598)),
        ),
    ]
