# Generated by Django 2.0.2 on 2018-02-11 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0021_auto_20180211_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation_Calender_Setting',
            new_name='ReservationCalenderSetting',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 37, 48, 414033)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 37, 48, 414033)),
        ),
    ]
