# Generated by Django 2.0.2 on 2018-02-11 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0023_auto_20180211_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationcalendersetting',
            name='last_session_time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 19, 6, 14, 505081)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 19, 6, 14, 505081)),
        ),
    ]
