# Generated by Django 2.0.2 on 2018-02-12 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0027_auto_20180211_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 13, 0, 35, 40, 85497)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_end',
            field=models.TimeField(default=datetime.datetime(2018, 2, 13, 0, 35, 40, 86000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_start',
            field=models.TimeField(default=datetime.datetime(2018, 2, 13, 0, 35, 40, 86000)),
        ),
    ]
