# Generated by Django 2.0.2 on 2018-02-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0030_auto_20180213_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime_start',
            new_name='time_start',
        ),
    ]
