# Generated by Django 2.0.2 on 2018-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0032_auto_20180215_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
