# Generated by Django 2.0.2 on 2018-02-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0033_auto_20180215_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationCalenderSetting',
            new_name='CalenderSetting',
        ),
    ]
