# Generated by Django 2.0.2 on 2018-02-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_setting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image',
            field=models.ImageField(default='img/homepage/logo.png', upload_to='img/homepage'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
