# Generated by Django 2.0.2 on 2018-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180210_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='image',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='setting',
            name='navbar_brand',
            field=models.ImageField(default='img/homepage/logo.png', upload_to='img/homepage'),
        ),
    ]
