# Generated by Django 2.0.2 on 2018-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180210_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='background_image',
            field=models.ImageField(default='img/homepage/logo.png', upload_to='homepage'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='navbar_brand',
            field=models.ImageField(default='img/homepage/logo.png', upload_to='homepage'),
        ),
    ]
