# Generated by Django 2.0.2 on 2018-03-26 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180211_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of user who supplied request', max_length=50)),
                ('email', models.EmailField(help_text='Contact details of contacter', max_length=254)),
                ('subject', models.CharField(help_text='subject matter of message', max_length=50)),
                ('message', models.CharField(help_text='message', max_length=500)),
            ],
        ),
    ]
