# Generated by Django 2.0.2 on 2018-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(help_text='message'),
        ),
    ]
